//pruebas
POST http://localhost:8080/api/notes
    Content-Type: application/json

    {
        "body": "Contenido de la nota 5"
    }


###pruebas de get

GET  http://localhost:8080/api/notes


###pruebas de put
PUT http://localhost:8080/api/notes/5
    Content-Type: application/json

    {
    "important" : true
       
    }

###prueba de deleted
DELETE http://localhost:8080/api/notes/2
